### ISSUE TITLE
get_efficiency not working

### ISSUE THREAD

**Issue by fmathews11** [j-andrews7/kenpompy#10]
Greetings!  I may be overlooking something simple here, but when I run the example provided on the readme, I get an error:

`~\anaconda3\lib\site-packages\kenpompy\summary.py in get_efficiency(browser, season)
     37         browser.open(url)
     38         eff = browser.get_current_page()
---> 39         table = eff.find_all('table')[0]
     40         eff_df = pd.read_html(str(table))
     41 

IndexError: list index out of range`

**Comment by j-andrews7** [comment]
Yeah, pretty sure the HTML on the site changed slightly. I think there's a
PR that fixes this. I have some time Friday so I'll take a look then and
try to get a new release out that fixes this.

**Comment by j-andrews7** [comment]
I was unable to replicate this. Did you login properly?

**Comment by fmathews11** [comment]
Not exactly sure what/why/how, but re-ran the same code and it appears to be working now.
