### ISSUE TITLE
Link not found issue

### ISSUE THREAD

**Issue by jgpayne** [j-andrews7/kenpompy#102]
raise LinkNotFoundError()
    mechanicalsoup.utils.LinkNotFoundError
   
I'm getting this error when trying to log in using kenpompy. I'm using python3.10. I saw some similar issues a couple years ago and saw it may have been fixed. Everything has been working so far this week, up until today. Is this something in the new release that will be fixed?

**Comment by j-andrews7** [comment]
These have been difficult issues to troubleshoot in the past. Cloudflare is constantly changing.

Our tests for the new release are passing, so you might try that branch. Upgrading to python 3.11 _might_ fix it as well. I'll get the new release on PyPi this weekend.

**Comment by j-andrews7** [comment]
I've just made a new release that should deal with most of these issues. Please re-install from PyPi and let me know if you're still hitting problems.

**Comment by jgpayne** [comment]
Things are looking good at the moment, I have some more things running in the morning and will report back

**Comment by jgpayne** [comment]
Looks like everything is working for me! Thanks for the release!
