### ISSUE TITLE
Team Schedule

### ISSUE THREAD

**Issue by dmeredith3** [j-andrews7/kenpompy#14]
First, thanks for making this! Its helped me out a lot. I am trying to pull all of the teams schedules from the website and when it gets to teams like Texas A&M or North Carolina A&T the kenpompy.team.get_schedule() fails. Looking at the code it looks like this is because it doesn't adjust for the fact that when the url has a & in it it is replaced by "%26". For example the url for Texas A&M should be https://kenpom.com/team.php?team=Texas+A%26M and not https://kenpom.com/team.php?team=Texas+A&M.

**Comment by tom-wagner** [comment]
Tackling this now locally, think it will be:

team = team.replace("&", "%26")

**Comment by j-andrews7** [comment]
Sorry for the delay on this one, I'll try to take a look this weekend.
