### ISSUE TITLE
Use of implicit RegExp in Series.str.replace is deprecated

### ISSUE THREAD

**Issue by esqew** [j-andrews7/kenpompy#18]
The Pandas maintainers have [deprecated the use of the implicit `regex=True` flag for `Series.str.replace` in December 2020](https://pandas.pydata.org/docs/whatsnew/v1.2.0.html#deprecations), which means a future release will break the current use without explicitly setting this flag:

> The default value of `regex` for [`Series.str.replace()`](https://pandas.pydata.org/docs/reference/api/pandas.Series.str.replace.html#pandas.Series.str.replace) will change from `True` to `False` in a future release. In addition, single character regular expressions will not be treated as literal strings when `regex=True` is set ([GH24804](https://github.com/pandas-dev/pandas/issues/24804))

As such, calls to `kenpompy` methods that reply on the implicit `regex=True` have begun printing `FutureWarning`s at runtime:

> `/kenpompy/kenpompy/summary.py:111: FutureWarning: The default value of regex will change from True to False in a future version.`

**Comment by j-andrews7** [comment]
Thanks for the PRs. Don't suppose you'd like to take a crack at fixing the other FutureWarnings as well?

Lots of `FutureWarning: Columnar iteration over characters will be deprecated in future releases.` warnings popping, but it's a pretty easy fix (see below).

https://stackoverflow.com/questions/61313365/pandas-futurewarning-columnar-iteration-over-characters-will-be-deprecated-in-f

**Comment by esqew** [comment]
I'd love to - should have some time later this week to take a crack at it.

**Comment by esqew** [comment]
As an update - just added https://github.com/j-andrews7/kenpompy/pull/20/commits/bc1f0f624d71e4a90c57e8be58b4608f8a18b342 to the PR branch which should resolve all the `FutureWarning`s that are popped in the test suite
