### ISSUE TITLE
CI/CD credentials expired

### ISSUE THREAD

**Issue by esqew** [j-andrews7/kenpompy#36]
Hi @j-andrews7 - looks like your KenPom premium access may have expired recently. Tests in the `dev` branch started failing about a week or so ago, and further [printing of the locals shows the subscription of the account configured for CI/CD expired 11/14/22](https://github.com/j-andrews7/kenpompy/actions/runs/3535205159/jobs/5932955230#step:5:181).

If you'd prefer, I can coordinate to have my credentials synced as the environment variables here.

**Comment by j-andrews7** [comment]
Woops, yeah, they did. Sorry, holidays and paper revisions. Will renew
tomorrow when I get a chance.

**Comment by j-andrews7** [comment]
Renewed, tests passing.

**Comment by esqew** [comment]
Thanks!
