### ISSUE TITLE
Misc.Get_Pomeroy_Ratings() returning incorrect names in the 'Team' field

### ISSUE THREAD

**Issue by Tim-Romer** [j-andrews7/kenpompy#41]
Hi Team,

I found an issue when pulling the Ratings table by calling the misc.get_pomeroy_ratings(browser) method. It seems that some of the team names are being cut off. I noticed that team names with > 1 whitespace (ex. Cal St. Northridge) and team names that contain characters that aren't "A-Z" or "." (ex. Saint Mary's, Texas A&M). Below are a few of the problematic team names I found:

| Correct Team Name | Team Name from data pull |
| --------------------- | ----------------------------- |
| Saint Mary's | Saint Mary |
| San Diego St. | San Diego |
| Sam Houston St. | Sam Houston |
| Texas A&M | Texas A |
| etc. | etc. |

I found this issue that has been closed and it seems to be related: #9 

I believe the issue has to do with the regex in misc.py line 35:
`tmp = ratings_df['Team'].str.extract(r'(?P<Team>[a-zA-Z.]+\s*[a-zA-Z]+\.*)\s*(?P<Seed>\d*)')`

Let me know what y'all think. Happy to provide a more complete list of team names that are not correct if needed.

Thanks!

**Comment by j-andrews7** [comment]
Bah, thought we'd fixed this. We should probably throw in a few test cases
for these.

I'm pretty slammed but will take a look when I get a chance if Sean doesn't
beat me to it.

**Comment by esqew** [comment]
Sorry I've been MIA for a bit - work has really been kicking my butt on top of the fact that I'm also in the middle of moving... ha!

I'm fairly sure I also have a patch for this in `dev` branch but we'll deal with that in the inevitable merge. Thanks for the report @Tim-Romer and for the patch @nickostendorf. Closing as this was merged to `master` in 5ca349ec65983e978daffe815e53b77cd28cd7fd
