### ISSUE TITLE
FanMatch Conference Tourneys impacting team name parsing

### ISSUE THREAD

**Issue by nickostendorf** [j-andrews7/kenpompy#47]
@j-andrews7 @esqew 

With the conference tournaments going on this week, I noticed some of the FanMatch output showing the conference tournament name in them.

![FanMatch errors](https://user-images.githubusercontent.com/3138933/222874442-3a188239-83cf-4096-a933-4533731ad55f.png)

I ran the FanMatch module and stepped through the logic for 3/3. 
I noticed that if the home team is the PredictedLoser and it is a conference tourney game, then the result of the team name will include the tournament abbreviation.
However, if the above scenario is not true, then the conference tourney is parsed to the possessions column. 

Here is how the PredictedLoser is getting parsed for the above scenario.
It is retrieving everything after the team's ranking, therefore adding tourney abbreviation.
```
x[0] = " ".join(x[0].split()[1:])
x[1] = " ".join(x[1].split()[1:])
``` 
and here is the logic for how possessions are getting parsed:
```
pos = fm_df.Game.str.split(r" \[").str[1]
fm_df["Game"], fm_df["Possessions"] = fm_df.Game.str.split(r" \[").str[0], pos.astype("str")
fm_df.Possessions = fm_df.Possessions.str.strip(r"\]")
```

This is just a string splitting issue. I was wondering if either of you guys had any ideas on how to go about this.
We could create a list of conference tourney's and remove them from the `Game` column as soon as we retrieve the FanMatch table. Obviously, we would need to collect all of KenPom's tourney abbreviations for this to work without error.

Thanks, let me know what you think.

**Comment by esqew** [comment]
Good call out. The ideal solution is to just tighten up on the pattern matching to account for the conference tournament level potentially being present along this time of year. It would be significantly preferable to avoid having to hard-code any conference labeling data so as to eliminate the resulting maintenance overhead.

This should be a somewhat easy fix for someone with the right level of RegExp knowledge. I'll have time to take a peek at this on Monday at the latest.

**Comment by nickostendorf** [comment]
Yeah I think Regex is probably the best way to alleviate errors in the long run. 

I did just work up a quick fix for the time being if anyone needs a solution:
- Pulled all unique conferences from the Kenpom summary page and added '-T' to the end of all labels
- Created a variable self.conf_tourneys to hold the [labels](https://gist.github.com/nickostendorf/d847ec0abd3ca44d291a9e9b721d10e3)

And added this before any other parsing begins:
```
p = re.compile('|'.join(map(re.escape, self.conf_tourneys)))
fm_df['Game'] = [p.sub('', tourney) for tourney in fm_df['Game']]
```

This is not a concrete solution as labels can change over time like you said. I'll look into some Regex and poke at it some more.

Let me know if you find a better solution!

**Comment by j-andrews7** [comment]
Seems a pretty easy grep/regex with "-T". I won't have time to mess with
this for at least a few weeks, but if somebody makes a PR and includes a
test for stripping or including this info, I'd welcome it.
