### ISSUE TITLE
Add pulling stats by Conference

### ISSUE THREAD

**Issue by WakeUpWaffles** [j-andrews7/kenpompy#49]
I have implemented pulling stats by conferences. They're pulled from this [url](https://kenpom.com/conf.php?c=B10). #50 

It currently pulls:
- Conference ids for a given season
- Aggregate stats for the whole conference
- Standing stats
- Offense stats
- Defense stats

Let me know if there are any changes/additions for the conferences page.
Logan

**Comment by esqew** [comment]
We'll track on this in the PR itself (#50).
