### ISSUE TITLE
Error with Dataframe column mapping for get_playerstats()

### ISSUE THREAD

**Issue by cjt243** [j-andrews7/kenpompy#5]
For 2P, 3P and FT metrics, the column mapping is 7 elements instead of 9.

![image](https://user-images.githubusercontent.com/36831519/76236844-a9b72f00-6203-11ea-9ea7-c1363bf5c413.png)

And missing (2P for example):
![image](https://user-images.githubusercontent.com/36831519/76236912-c489a380-6203-11ea-884b-b1477887aa9f.png)

So the 2P% is fitting, but the column mapping isn't accounting for attempts and makes.

**Comment by cjt243** [comment]
I added an additional elif to the get_playerstats() function that essentially cleans up the dataframe properly (albeit a bit hacky):
`ps_df.columns = ['Rank', 'Player', 'Team', metric.replace('%','M'), metric.replace('%','A'), metric, 'Ht', 'Wt', 'Yr']`

**Comment by j-andrews7** [comment]
Can you give me a reproducible call? I'll take a look at this sometime this
week if I get a chance.

**Comment by j-andrews7** [comment]
This is indeed an oversight for 2P%, 3P%, and FT% metrics. I will push a fix soon.

**Comment by j-andrews7** [comment]
This is fixed in a new release, v0.2.1. Thanks for reporting.

**Comment by cjt243** [comment]
No problem, glad to help! Love the package btw
