### ISSUE TITLE
Additional components from KenPom scouting reports

### ISSUE THREAD

**Issue by ddogwoofwoof** [j-andrews7/kenpompy#62]
In KenPom's scouting reports, there are Miscellaneous and Style Components, such as Non-Stl TO%, 3PA/FGA, and A/FGM, that are not available using the summary.py file. Do you know if we can add those in?
Thank you!
Derek

**Comment by esqew** [comment]
Yes, we can definitely target these Scouting Report items for inclusion in `team.py`. I'll do some more digging on my own, but if you're so inclined feel free to open a PR for this.

**Comment by ddogwoofwoof** [comment]
@esqew will do! I really appreciate your support on this
