### ISSUE TITLE
"Conference only" filter in KenPom Scouting Reports

### ISSUE THREAD

**Issue by ddogwoofwoof** [j-andrews7/kenpompy#63]
In KenPom's scouting reports, there is a "Conference only" filter. Unfortunately, I don't see this filter option using the summary.py file. Do you know if this is possible to include? I inspected KenPom's website, but struggled to find the elements that include this info.
Thank you!
Derek

**Comment by j-andrews7** [comment]
Those are tricky, as it requires interacting with the page in a difficult
way. We'd like to add them, but it's not straight forward. I can't remember
if we figured out a way to do so on the other pages yet or not.

We'll probably push a release before the season kicks off fully to adjust
for changes he's made to the site since the end of last season.

**Comment by ddogwoofwoof** [comment]
That makes sense. I'll take a stab at it as well and create a pull request if I can make progress. Thank you!

**Comment by esqew** [comment]
I believe what you're referring to is something that has already had work put forward in #40. It's currently stalled for a variety of reasons, the biggest of which being that I'm not convinced we should take additional overhead to execute arbitrary JavaScript for support of such a small sliver of the site.

I have a local branch where I've tried to do this purely with the current dependency set and parsing some of the JS content with a thoughtful RegExp but it's not yet all the way there.

If you are so inclined, please feel free to try to pull together a PR and we'd be more than happy to consider it.

**Comment by esqew** [comment]
> I have a local branch where I've tried to do this purely with the current dependency set and parsing some of the JS content with a thoughtful RegExp but it's not yet all the way there.

I just now remembered my attempt at this has actually been pushed to the [enhancement/team-scouting-report](https://github.com/j-andrews7/kenpompy/tree/enhancement/team-scouting-report) branch

**Comment by ddogwoofwoof** [comment]
@esqew this is perfect!! Thank you so much for sharing!
