### ISSUE TITLE
Team names are incorrect when grabbing kenpom rankings

### ISSUE THREAD

**Issue by jgpayne** [j-andrews7/kenpompy#65]
when using kenpompy.misc.get_pomeroy_ratings names get cut off. For example there are three Cal St. when one should be Cal St. Fullerton, Cal St. Northridge etc.

**Comment by j-andrews7** [comment]
~~All those juco California teams are the same.~~ Thanks for the report. Regex woes strike again. We'll try to fix this for our start of season release.

**Comment by j-andrews7** [comment]
See #9 and #41 for previous issues with this. #42 was our last fix four this, I believe.

**Comment by jgpayne** [comment]
No worries! There is a workaround using get valid team names, but just wanted to bring it to your attention!

**Comment by esqew** [comment]
I believe #42 did fix this since I can't repro this when using the latest commit:

```
from kenpompy.utils import login
browser = login('[redacted]', '[redacted]')

from kenpompy.misc import get_pomeroy_ratings
df = get_pomeroy_ratings(browser=browser)
df[df['Team'].str.startswith('Cal')]['Team']
```

Result:
```
145             California
173      Cal St. Fullerton
180            Cal Baptist
277    Cal St. Bakersfield
321     Cal St. Northridge
340               Cal Poly
Name: Team, dtype: object
```

If you're still using the version that's on PyPi (released 12-2022), that doesn't yet have this patch (01-2023).

**Comment by pstonebu** [comment]
Not specific to the California teams, but the team name grabbing is still not working exactly right. For example, both "South Carolina" and "South Carolina State" become "South Carolina." Can use conf to differentiate, but it's still a bit confusing. Alabama A&M gets stored as "Alabama A," Arkansas Pine Bluff is "Arkansas Pine," etc.

**Comment by j-andrews7** [comment]
Did you install from GitHub? If not, the version on pypi will still have
these issues that should be fixed in the dev version. Once we get
outstanding PRs rolled in, we'll push a new release to pypi.

**Comment by pstonebu** [comment]
Thought I had updated kenpompy from git but evidently not. An uninstall and reinstall from git fixed it. Thanks!
