### ISSUE TITLE
Add tests for appropriate parsing of team names

### ISSUE THREAD

**Issue by j-andrews7** [j-andrews7/kenpompy#66]
See #9, #41, #65 for instances where team names with special characters (especially ".") are not parsed correctly. We should add a test or two for this in `test_team.py`, `test_misc.py`, and `test_summary.py`.

**Comment by Shreya111111** [comment]
@j-andrews7 can i work on this issue

**Comment by j-andrews7** [comment]
Go wild, we welcome PRs.
