### ISSUE TITLE
Properly handle team-specific data availability for certain years

### ISSUE THREAD

**Issue by esqew** [j-andrews7/kenpompy#68]
Related to #64 - some teams have data missing for years that other teams do not. For example, most/all top-tier D1 programs have been in D1 for quite some time and thus have the complete dataset from 1999 all the way through present day.

However, more recent D-1 admits will have limited historical availability. See [Merrimack](https://kenpom.com/team.php?team=Merrimack), who has data only beginning in 2020.

This also means that any team between 1999 and present who (a) was in D-1, (b) did not participate in D-1 for one or more years, then (c) returned to D-1 may also have some years missing in between.

A simple solution for this is a check to make sure the navigation to a particular team's season page in `team.py` is not redirected back to the main page (which seems to be how KenPom is designed to behave when requesting data that doesn't exist; see how https://kenpom.com/team.php?team=Merrimack&y=2019 behaves).

**Comment by esqew** [comment]
I drew this up quickly in my JavaScript console when I had a second today:

    [...document.querySelector('#years-wrapper #years-container').innerText.matchAll(/(?<=\s)\d{2}(?=\s)/g)].map(_ => parseInt(_[0]) > parseInt(new Date().getYear().toString().substring(1)) + 1 ? '19' + _[0] : '20' + _[0])

When run against [Villanova's team page](https://kenpom.com/team.php?team=Villanova) returns:

    ['1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']

**Comment by j-andrews7** [comment]
Go for it, PRs are welcome. We'll probably push a release here relatively
soon.

**Comment by esqew** [comment]
As @WakeUpWaffles mentioned in the thread for #75, this is actually already handled with appropriate calls to `get_valid_teams()`
