### ISSUE TITLE
Build URLs with urllib instead of manually

### ISSUE THREAD

**Issue by esqew** [j-andrews7/kenpompy#70]
Nice to have: a much cleaner way to generate the target scraping URLs and their parameters would be to use [`urllib.parse.urlencode`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode), which would preclude us from having to do escapes, etc. ourselves.

A non-exhaustive list of some examples of where this could be leveraged:

* https://github.com/j-andrews7/kenpompy/blob/378b5e2999b8858d4b2cc749ecdf2d4a73ff50e5/kenpompy/team.py#L24
* https://github.com/j-andrews7/kenpompy/blob/378b5e2999b8858d4b2cc749ecdf2d4a73ff50e5/kenpompy/team.py#L84-L87
* https://github.com/j-andrews7/kenpompy/blob/378b5e2999b8858d4b2cc749ecdf2d4a73ff50e5/kenpompy/summary.py#L35
* https://github.com/j-andrews7/kenpompy/blob/378b5e2999b8858d4b2cc749ecdf2d4a73ff50e5/kenpompy/summary.py#L93
* https://github.com/j-andrews7/kenpompy/blob/378b5e2999b8858d4b2cc749ecdf2d4a73ff50e5/kenpompy/summary.py#L145

**Comment by Wolfmyths** [comment]
Hey I'd like to take a look at this issue, but before I do. Would you rather have urls formatted like this?
```py
# Current Format
url = url + '?' + urllib.parse.urlencode({"y":str(season)})
# New Format
url = f'{url}?{urllib.parse.urlencode({"y":str(season)})}'
```

We could also do something like this
```py
url += f'?{urllib.parse.urlencode({"y":str(season)})}'
```

**Comment by esqew** [comment]
The first would be most preferable, however we generally put more of an emphasis on readability than most other projects. Something akin to the following would be preferable:

    params = {}
    if season:
        params['y'] = str(season)

    url = url + '?' + urllib.parse.urlencode({"y":str(season)})
