### ISSUE TITLE
get_pomeroy_ratings producing unexpected results

### ISSUE THREAD

**Issue by caseydunlap** [j-andrews7/kenpompy#77]
![Capture](https://github.com/j-andrews7/kenpompy/assets/117862701/4712d7c1-c705-444b-bc38-93b644428830)

Don't think this is right?

**Comment by j-andrews7** [comment]
This has probably been fixed in the dev version. If you install directly
from GitHub, it will (probably) be fixed. We had a parsing issue or two.
Stretched for time but will try to get a release out soon to pypi.

**Comment by caseydunlap** [comment]
![image](https://github.com/j-andrews7/kenpompy/assets/117862701/ab722c85-84df-4a04-bf05-13589c7def4a)

Yep that did it. Support above. Thanks.

**Comment by caseydunlap** [comment]
![image](https://github.com/j-andrews7/kenpompy/assets/117862701/4503775b-1f77-47ba-bfa2-372dc7d3840f)

Yep that did it. Support embedded. Thanks.
