### ISSUE TITLE
2020 COVID year

### ISSUE THREAD

**Issue by jmislansky** [j-andrews7/kenpompy#81]
In team.py, I would add the line below line 33. There is an asterisk in this year since the seeds aren't the actual tourney seeds. Otherwise if you search for a team that was ranked, it returns an error

`team_df = team_df.str.replace(r'\*', '', regex=True)`

**Comment by esqew** [comment]
I am almost inclined to include a runtime warning of some sort that mentions that the data being pulled contains this "speculative" information, but that's more nice-to-have than anything else.
