### ISSUE TITLE
CI/CD: Rate limiting between cases

### ISSUE THREAD

**Issue by esqew** [j-andrews7/kenpompy#85]
Our test suite has been getting tripped up by a seemingly more aggressive Cloudflare rate limit, especially when calling `misc.py::get_current_season()` ([here's a recent example](https://github.com/j-andrews7/kenpompy/actions/runs/7037966790/job/19153895919#step:5:189)).

While I'm doing a bit of finalization on the analysis to confirm this fact, I would propose we let the test suite "breathe" for a few seconds between cases to avoid consistently tripping this rate limit.

This will definitely increase the total time required to run the whole suite but I believe the trade-off is more than acceptable.

**Comment by j-andrews7** [comment]
Yeah, I've noticed this a time or two, probably a smart idea. The tests are already pretty quick, even doubling the time they take won't really matter, the env build takes way longer.

**Comment by tom-wagner** [comment]
Does anyone have any idea how many request in X seconds / minutes will trip the rate limiter? I have some scripts that make a ton of calls and curious how much I should slow my code down in my jitter implementation

**Comment by j-andrews7** [comment]
Couldn't tell you, but I'd try to keep it to a few per second max. Ken was
fine with this software so long as it's used responsibly and doesn't impact
the site.

And most modern sites should be able to easily handle a few requests per
second. Couldflare might pop, but I think we've largely gotten around that.
I don't get much feedback from users, so if you run into limits let me know
so I can provide better guidance in the docs.

**Comment by esqew** [comment]
Based on what I know having done implementations of Cloudflare and similar products for clients, there is likely no one standard rate limit in use. Cloudflare in particular uses a huge number of heuristics with requests over time being just one of many they use to determine how to respond to a given request.

In short: use good judgment. There will be a happy medium between not limiting your requests at all and forcing your loops through digital molasses
